import redYellowLogo from './mcd-logo-red-yellow.png'
import whiteLogo from './mcd-logo-white.png'
import mcChickenMeal from './mc-chicken-meal.jpg'
import mcChickenMealNoBG from './mc-chicken-meal-no-bg.png'
import mcdBurgerPNG from './mcd-burger-no-bg.png'
import ingredients from './ingredients.jpg'
import grills from './grills.jpg'
import delivery from './delivery.jpg'
import nonHalal from './non-halal.png'
import halal from './halal-icon.png'
import combo from './combo.png'
import breakfast from './english-breakfast.png'
import drinks from './soda.png'
import burger from './burger.png'
import desserts from './ice-cream.png'
import fries from './french-fries.png'
import nuggets from './nuggets.png'
import popular from './flame.png'
import price from './price-tag.png' 
import register from './register_photo.jpg'

export { redYellowLogo,whiteLogo, mcChickenMeal, mcChickenMealNoBG, mcdBurgerPNG, ingredients, grills, delivery, nonHalal, halal, combo, breakfast, drinks, burger, desserts, fries, nuggets, popular, price, register}